/**
 * @since 4.0.0
 */
import * as Predicate from "../data/Predicate.ts"
import type * as Record from "../data/Record.ts"
import { formatPath, hasOwn } from "../internal/schema/util.ts"
import type * as Annotations from "./Annotations.ts"
import * as AST from "./AST.ts"
import type * as Check from "./Check.ts"
import type * as Schema from "./Schema.ts"

/**
 * @since 4.0.0
 */
export type Type = "string" | "number" | "boolean" | "array" | "object" | "null" | "integer"

/**
 * @since 4.0.0
 */
export type JsonSchema = {
  type?: Type
  [x: string]: unknown
}

/**
 * @since 4.0.0
 */
export type JsonSchemaFragment = {
  [x: string]: unknown
}

/**
 * @since 4.0.0
 */
export declare namespace Annotation {
  /**
   * @since 4.0.0
   */
  export type ConstraintContext = {
    /** The target of the JSON Schema */
    readonly target: Target
    /** The type of the JSON Schema */
    readonly type?: Type | undefined
  }

  /**
   * @since 4.0.0
   */
  export type Constraint = {
    readonly _tag: "Constraint"
    readonly constraint: (context: ConstraintContext) => JsonSchemaFragment | undefined
  }

  /**
   * @since 4.0.0
   */
  export type OverrideContext = {
    /** The target of the JSON Schema */
    readonly target: Target
    /** The JSON Schema that would be generated by the AST */
    readonly jsonSchema: JsonSchema
    /** A function that generates a JSON Schema from an AST */
    readonly make: (ast: AST.AST) => JsonSchema
  }

  /**
   * @since 4.0.0
   */
  export type Override = {
    readonly _tag: "Override"
    readonly override: (context: OverrideContext) => JsonSchema
    /** Whether the override is required */
    readonly required?: boolean | undefined
  }
}

/**
 * @since 4.0.0
 */
export type Target = "draft-07" | "draft-2020-12" | "openApi3.1"

/**
 * @since 4.0.0
 */
export type AdditionalPropertiesStrategy = "allow" | "strict"

/**
 * @since 4.0.0
 */
export type TopLevelReferenceStrategy = "skip" | "keep"

/**
 * @since 4.0.0
 */
export interface BaseOptions {
  readonly definitions?: Record<string, JsonSchema> | undefined
  readonly getRef?: ((id: string) => string) | undefined
  readonly additionalPropertiesStrategy?: AdditionalPropertiesStrategy | undefined
  readonly topLevelReferenceStrategy?: TopLevelReferenceStrategy | undefined
}

/**
 * @since 4.0.0
 */
export interface Draft07_Options extends BaseOptions {}

/**
 * Returns a JSON Schema Draft 07 object.
 *
 * @since 4.0.0
 */
export function makeDraft07<S extends Schema.Top>(schema: S, options?: Draft07_Options): JsonSchema {
  return make(schema, { ...options, target: "draft-07" })
}

/**
 * @since 4.0.0
 */
export interface Draft2020_12_Options extends BaseOptions {}

/**
 * Returns a JSON Schema Draft 2020-12 object.
 *
 * **OpenAPI 3.1**
 *
 * OpenAPI 3.1 schemas are fully compatible with JSON Schema Draft 2020-12 (see
 * OpenAPI Initiative blog announcement, February 18 2021)
 *
 * @since 4.0.0
 */
export function makeDraft2020_12<S extends Schema.Top>(schema: S, options?: Draft2020_12_Options): JsonSchema {
  return make(schema, { ...options, target: "draft-2020-12" })
}

/**
 * @since 4.0.0
 */
export interface OpenApi3_1Options extends BaseOptions {}

/**
 * @since 4.0.0
 */
export function makeOpenApi3_1<S extends Schema.Top>(schema: S, options?: OpenApi3_1Options): object {
  return make(schema, { ...options, target: "openApi3.1" })
}

interface Options extends Draft07_Options {
  readonly target?: Target | undefined
}

function get$schema(target: Target) {
  switch (target) {
    case "draft-07":
      return "http://json-schema.org/draft-07/schema"
    case "draft-2020-12":
    case "openApi3.1":
      return "https://json-schema.org/draft/2020-12/schema"
  }
}

function make<S extends Schema.Top>(schema: S, options?: Options): JsonSchema {
  const definitions = options?.definitions ?? {}
  const getRef = options?.getRef ?? ((id: string) => "#/$defs/" + id)
  const target = options?.target ?? "draft-07"
  const additionalPropertiesStrategy = options?.additionalPropertiesStrategy ?? "strict"
  const topLevelReferenceStrategy = options?.topLevelReferenceStrategy ?? "keep"
  const skipId = topLevelReferenceStrategy === "skip"
  const out: JsonSchema = {
    $schema: get$schema(target),
    ...go(schema.ast, [], {
      definitions,
      getRef,
      target,
      additionalPropertiesStrategy
    }, skipId)
  }
  if (Object.keys(definitions).length > 0) {
    out.$defs = definitions
  }
  return out
}

function isContentEncodingSupported(target: Target): boolean {
  switch (target) {
    case "draft-07":
      return false
    case "draft-2020-12":
    case "openApi3.1":
      return true
  }
}

function getJsonSchemaAnnotations(
  target: Target,
  annotations: Annotations.Annotations | undefined
): JsonSchemaFragment | undefined {
  if (annotations) {
    const out: JsonSchemaFragment = {}
    if (hasOwn(annotations, "title") && Predicate.isString(annotations.title)) {
      out.title = annotations.title
    }
    if (hasOwn(annotations, "description") && Predicate.isString(annotations.description)) {
      out.description = annotations.description
    }
    if (hasOwn(annotations, "default")) {
      if (annotations.default !== undefined) {
        out.default = annotations.default
      }
    }
    if (hasOwn(annotations, "examples") && Array.isArray(annotations.examples)) {
      const examples = annotations.examples.filter((example) => example !== undefined)
      if (examples.length > 0) {
        out.examples = examples
      }
    }
    if (hasOwn(annotations, "format") && Predicate.isString(annotations.format)) {
      out.format = annotations.format
    }
    if (isContentEncodingSupported(target)) {
      if (hasOwn(annotations, "contentEncoding") && Predicate.isString(annotations.contentEncoding)) {
        out.contentEncoding = annotations.contentEncoding
      }
    }
    return Object.keys(out).length > 0 ? out : undefined
  }
}

function getAnnotation(
  annotations: Annotations.Annotations | undefined
): Annotation.Override | Annotation.Constraint | undefined {
  return annotations?.jsonSchema as Annotation.Override | Annotation.Constraint | undefined
}

function getCheckJsonFragment<T>(
  check: Check.Check<T>,
  target: Target,
  type?: Type
): JsonSchemaFragment | undefined {
  const annotation = getAnnotation(check.annotations)
  if (annotation && annotation._tag === "Constraint") {
    return annotation.constraint({ target, type })
  }
}

function getChecksJsonFragment(
  ast: AST.AST,
  target: Target,
  type?: Type
): JsonSchemaFragment | undefined {
  let out: JsonSchemaFragment & { allOf: Array<unknown> } = {
    ...getJsonSchemaAnnotations(target, ast.annotations),
    allOf: []
  }
  if (ast.checks) {
    function handle(check: Check.Check<any>) {
      const fragment: JsonSchemaFragment = {
        ...getJsonSchemaAnnotations(target, check.annotations),
        ...getCheckJsonFragment(check, target, type)
      }
      if (hasOwn(fragment, "type")) {
        out.type = fragment.type
        delete fragment.type
      }
      if (Object.keys(fragment).some((k) => hasOwn(out, k))) {
        out.allOf.push(fragment)
      } else {
        out = { ...out, ...fragment }
      }
    }
    function go(check: Check.Check<any>) {
      handle(check)
      if (check._tag === "FilterGroup") {
        check.checks.forEach(go)
      }
    }
    ast.checks.forEach(go)
  }
  if (out.allOf.length === 0) {
    delete (out as any).allOf
  }
  return out
}

/** Either the AST is optional or it contains an undefined keyword */
function isLooseOptional(ast: AST.AST): boolean {
  const annotation = getAnnotation(ast.annotations)
  if (annotation && annotation._tag === "Override" && annotation.required === true) {
    return false
  }
  return AST.isOptional(ast) || AST.containsUndefined(ast)
}

function getPattern(
  ast: AST.AST,
  path: ReadonlyArray<PropertyKey>,
  options: GoOptions,
  ignoreErrors: boolean
): string | undefined {
  switch (ast._tag) {
    case "StringKeyword": {
      const json = go(ast, path, options)
      if (hasOwn(json, "pattern") && Predicate.isString(json.pattern)) {
        return json.pattern
      }
      return undefined
    }
    case "NumberKeyword":
      return "^[0-9]+$"
    case "TemplateLiteral":
      return AST.getTemplateLiteralRegExp(ast).source
  }
  if (ignoreErrors) return undefined
  throw new Error(`cannot generate JSON Schema for ${ast._tag} at ${formatPath(path) || "root"}`)
}

type GoOptions = {
  readonly definitions: Record<string, JsonSchema>
  readonly getRef: (id: string) => string
  readonly target: Target
  readonly additionalPropertiesStrategy: AdditionalPropertiesStrategy
}

function getId(ast: AST.AST): string | undefined {
  const id = AST.getIdAnnotation(ast)
  if (id !== undefined) return id
  if (AST.isSuspend(ast)) {
    return getId(ast.thunk())
  }
}

/**
 * If the AST has checks, we look for an override annotation in the checks. If
 * not, we look for an override annotation or constraint annotation in the
 * annotations.
 */
function getBottomJsonSchemaAnnotation(ast: AST.AST): Annotation.Override | Annotation.Constraint | undefined {
  if (ast.checks) {
    for (let i = ast.checks.length - 1; i >= 0; i--) {
      const check = ast.checks[i]
      const annotation = getAnnotation(check.annotations)
      if (annotation && annotation._tag === "Override") {
        return annotation
      }
    }
  }
  return getAnnotation(ast.annotations)
}

function isCompactableLiteral(
  jsonSchema: JsonSchema | undefined
): jsonSchema is JsonSchema & { enum: Array<unknown> } {
  return jsonSchema !== undefined && "enum" in jsonSchema && "type" in jsonSchema &&
    Object.keys(jsonSchema).length === 2
}

function compactLiterals(members: Array<JsonSchema>) {
  const out: Array<JsonSchema> = []
  for (const m of members) {
    if (isCompactableLiteral(m) && out.length > 0) {
      const last = out[out.length - 1]
      if (isCompactableLiteral(last) && last.type === m.type) {
        out[out.length - 1] = {
          ...last,
          enum: [...last.enum, ...m.enum]
        }
        continue
      }
    }
    out.push(m)
  }
  return out
}

function go(
  ast: AST.AST,
  path: ReadonlyArray<PropertyKey>,
  options: GoOptions,
  ignoreId: boolean = false,
  ignoreAnnotation: boolean = false,
  ignoreErrors: boolean = false
): JsonSchema {
  // ---------------------------------------------
  // handle json schema annotations
  // ---------------------------------------------
  const target = options.target
  if (!ignoreAnnotation) {
    const annotation = getBottomJsonSchemaAnnotation(ast)
    if (annotation) {
      switch (annotation._tag) {
        case "Override":
          return annotation.override({
            target,
            jsonSchema: go(ast, path, options, ignoreId, true, true),
            make: (ast) => go(ast, path, options, ignoreId)
          })
        case "Constraint": {
          const jsonSchema = go(ast, path, options, ignoreId, true)
          return {
            ...jsonSchema,
            ...annotation.constraint({ target, type: jsonSchema.type })
          }
        }
      }
    }
  }
  // ---------------------------------------------
  // handle id annotation
  // ---------------------------------------------
  if (!ignoreId) {
    const id = getId(ast)
    if (id !== undefined) {
      if (Object.hasOwn(options.definitions, id)) {
        return options.definitions[id]
      } else {
        const escapedId = id.replace(/~/ig, "~0").replace(/\//ig, "~1")
        const out = { $ref: options.getRef(escapedId) }
        options.definitions[id] = out
        options.definitions[id] = go(ast, path, options, true)
        return out
      }
    }
  }
  // ---------------------------------------------
  // handle encoding
  // ---------------------------------------------
  if (ast.encoding) {
    return go(ast.encoding[ast.encoding.length - 1].to, path, options, ignoreId)
  }
  // ---------------------------------------------
  // handle base cases
  // ---------------------------------------------
  switch (ast._tag) {
    case "Declaration":
    case "BigIntKeyword":
    case "SymbolKeyword":
    case "UniqueSymbol": {
      if (ignoreErrors) return {}
      throw new Error(`cannot generate JSON Schema for ${ast._tag} at ${formatPath(path) || "root"}`)
    }
    case "UndefinedKeyword":
      return { not: {}, ...getChecksJsonFragment(ast, target) }
    case "VoidKeyword":
    case "UnknownKeyword":
    case "AnyKeyword":
      return { ...getChecksJsonFragment(ast, target) }
    case "NeverKeyword":
      return { not: {}, ...getChecksJsonFragment(ast, target) }
    case "NullKeyword": {
      const constraint = getChecksJsonFragment(ast, target, "null")
      return { type: "null", ...constraint }
    }
    case "StringKeyword":
      return { type: "string", ...getChecksJsonFragment(ast, target, "string") }
    case "NumberKeyword":
      return { type: "number", ...getChecksJsonFragment(ast, target, "number") }
    case "BooleanKeyword":
      return { type: "boolean", ...getChecksJsonFragment(ast, target, "boolean") }
    case "ObjectKeyword":
      return {
        anyOf: [
          { type: "object" },
          { type: "array" }
        ],
        ...getChecksJsonFragment(ast, target)
      }
    case "LiteralType": {
      if (Predicate.isString(ast.literal)) {
        return { type: "string", enum: [ast.literal], ...getChecksJsonFragment(ast, target, "string") }
      } else if (Predicate.isNumber(ast.literal)) {
        return { type: "number", enum: [ast.literal], ...getChecksJsonFragment(ast, target, "number") }
      } else if (Predicate.isBoolean(ast.literal)) {
        return { type: "boolean", enum: [ast.literal], ...getChecksJsonFragment(ast, target, "boolean") }
      }
      if (ignoreErrors) return {}
      throw new Error(`cannot generate JSON Schema for ${ast._tag} at ${formatPath(path) || "root"}`)
    }
    case "Enums": {
      return {
        ...go(AST.enumsToLiterals(ast), path, options),
        ...getChecksJsonFragment(ast, target)
      }
    }
    case "TemplateLiteral":
      return {
        type: "string",
        pattern: AST.getTemplateLiteralRegExp(ast).source,
        ...getChecksJsonFragment(ast, target, "string")
      }
    case "TupleType": {
      // ---------------------------------------------
      // handle post rest elements
      // ---------------------------------------------
      if (ast.rest.length > 1) {
        if (ignoreErrors) return {}
        throw new Error(
          "Generating a JSON Schema for post-rest elements is not currently supported. You're welcome to contribute by submitting a Pull Request"
        )
      }
      const out: JsonSchema = {
        type: "array",
        ...getChecksJsonFragment(ast, target, "array")
      }
      // ---------------------------------------------
      // handle elements
      // ---------------------------------------------
      const items = ast.elements.map((e, i) => ({
        ...go(e, [...path, i], options),
        ...getJsonSchemaAnnotations(target, e.context?.annotations)
      }))
      const minItems = ast.elements.findIndex(isLooseOptional)
      if (minItems !== -1) {
        out.minItems = minItems
      }
      // ---------------------------------------------
      // handle rest element
      // ---------------------------------------------
      const additionalItems = ast.rest.length > 0 ? go(ast.rest[0], [...path, ast.elements.length], options) : false
      if (items.length === 0) {
        out.items = additionalItems
      } else {
        switch (options.target) {
          case "draft-07": {
            out.items = items
            out.additionalItems = additionalItems
            break
          }
          case "draft-2020-12": {
            out.prefixItems = items
            out.items = additionalItems
            break
          }
        }
      }
      return out
    }
    case "TypeLiteral": {
      if (ast.propertySignatures.length === 0 && ast.indexSignatures.length === 0) {
        return {
          anyOf: [
            { type: "object" },
            { type: "array" }
          ],
          ...getChecksJsonFragment(ast, target)
        }
      }
      const out: any = {
        type: "object",
        ...getChecksJsonFragment(ast, target, "object")
      }
      // ---------------------------------------------
      // handle property signatures
      // ---------------------------------------------
      out.properties = {}
      out.required = []
      for (const ps of ast.propertySignatures) {
        const name = ps.name
        if (Predicate.isSymbol(name)) {
          if (ignoreErrors) return {}
          throw new Error(`cannot generate JSON Schema for ${ast._tag} at ${formatPath([...path, name]) || "root"}`)
        } else {
          out.properties[name] = {
            ...go(ps.type, [...path, name], options),
            ...getJsonSchemaAnnotations(target, ps.type.context?.annotations)
          }
          if (!isLooseOptional(ps.type)) {
            out.required.push(String(name))
          }
        }
      }
      // ---------------------------------------------
      // handle index signatures
      // ---------------------------------------------
      if (options.additionalPropertiesStrategy === "strict") {
        out.additionalProperties = false
      } else {
        out.additionalProperties = true
      }
      const patternProperties: Record<string, object> = {}
      for (const is of ast.indexSignatures) {
        const type = go(is.type, path, options)
        const pattern = getPattern(is.parameter, path, options, ignoreErrors)
        if (pattern !== undefined) {
          patternProperties[pattern] = type
        } else {
          out.additionalProperties = type
        }
      }
      if (Object.keys(patternProperties).length > 0) {
        out.patternProperties = patternProperties
        delete out.additionalProperties
      }
      return out
    }
    case "UnionType": {
      const members = compactLiterals(
        ast.types
          .filter((ast) => !AST.isUndefinedKeyword(ast)) // prune undefined
          .map((ast) => {
            const out = go(ast, path, options)
            if (path.length > 0) {
              return { ...out, ...getJsonSchemaAnnotations(target, ast.context?.annotations) }
            }
            return out
          })
      )
      switch (members.length) {
        case 0:
          return { not: {}, ...getChecksJsonFragment(ast, target) }
        case 1:
          return { ...members[0], ...getChecksJsonFragment(ast, target) }
        default:
          switch (ast.mode) {
            case "anyOf":
              return { "anyOf": members, ...getChecksJsonFragment(ast, target) }
            case "oneOf":
              return { "oneOf": members, ...getChecksJsonFragment(ast, target) }
          }
      }
    }
    case "Suspend": {
      const id = getId(ast)
      if (id !== undefined) {
        return go(ast.thunk(), path, options, true)
      }
      if (ignoreErrors) return {}
      throw new Error(
        `cannot generate JSON Schema for ${ast._tag} at ${formatPath(path) || "root"}, required \`id\` annotation`
      )
    }
  }
}
